//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.10 at 06:02:39 PM CET 
//


package com.example.patentservice.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Punomocnik }
     * 
     */
    public ZahtevZaPriznanjePatenta.Punomocnik createZahtevZaPriznanjePatentaPunomocnik() {
        return new ZahtevZaPriznanjePatenta.Punomocnik();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPronalazacu createZahtevZaPriznanjePatentaPodaciOPronalazacu() {
        return new ZahtevZaPriznanjePatenta.PodaciOPronalazacu();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciZavod }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciZavod createZahtevZaPriznanjePatentaPodaciZavod() {
        return new ZahtevZaPriznanjePatenta.PodaciZavod();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.NazivPronalaska }
     * 
     */
    public ZahtevZaPriznanjePatenta.NazivPronalaska createZahtevZaPriznanjePatentaNazivPronalaska() {
        return new ZahtevZaPriznanjePatenta.NazivPronalaska();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodnosilacPrijave }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodnosilacPrijave createZahtevZaPriznanjePatentaPodnosilacPrijave() {
        return new ZahtevZaPriznanjePatenta.PodnosilacPrijave();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.NacinDostavljanja }
     * 
     */
    public ZahtevZaPriznanjePatenta.NacinDostavljanja createZahtevZaPriznanjePatentaNacinDostavljanja() {
        return new ZahtevZaPriznanjePatenta.NacinDostavljanja();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Dopuna }
     * 
     */
    public ZahtevZaPriznanjePatenta.Dopuna createZahtevZaPriznanjePatentaDopuna() {
        return new ZahtevZaPriznanjePatenta.Dopuna();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava }
     * 
     */
    public ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava createZahtevZaPriznanjePatentaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return new ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava();
    }

    /**
     * Create an instance of {@link TNaziv }
     * 
     */
    public TNaziv createTNaziv() {
        return new TNaziv();
    }

    /**
     * Create an instance of {@link TKontakt }
     * 
     */
    public TKontakt createTKontakt() {
        return new TKontakt();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TAdresaDrzava }
     * 
     */
    public TAdresaDrzava createTAdresaDrzava() {
        return new TAdresaDrzava();
    }

    /**
     * Create an instance of {@link TKontaktFaks }
     * 
     */
    public TKontaktFaks createTKontaktFaks() {
        return new TKontaktFaks();
    }

    /**
     * Create an instance of {@link TDetaljiRanijePrijave }
     * 
     */
    public TDetaljiRanijePrijave createTDetaljiRanijePrijave() {
        return new TDetaljiRanijePrijave();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Punomocnik.Funkcija }
     * 
     */
    public ZahtevZaPriznanjePatenta.Punomocnik.Funkcija createZahtevZaPriznanjePatentaPunomocnikFunkcija() {
        return new ZahtevZaPriznanjePatenta.Punomocnik.Funkcija();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac }
     * 
     */
    public ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac createZahtevZaPriznanjePatentaPodaciOPronalazacuPronalazac() {
        return new ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac();
    }

}
