//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.10 at 06:02:39 PM CET 
//


package com.example.patentservice.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podaci_zavod"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="broj_prijave" type="{}TBroj_prijave"/&gt;
 *                   &lt;element name="datum_prijema" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="naziv_pronalaska"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="naziv" type="{}TNaziv" maxOccurs="2" minOccurs="2"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podnosilac_prijave"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;choice&gt;
 *                     &lt;sequence&gt;
 *                       &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
 *                       &lt;element name="drzavljanstvno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                     &lt;/sequence&gt;
 *                     &lt;element name="poslovno_ime" type="{}TVelika_slova"/&gt;
 *                   &lt;/choice&gt;
 *                   &lt;element name="lokacija" type="{}TAdresa_drzava"/&gt;
 *                   &lt;element name="kontakt" type="{}TKontakt_faks"/&gt;
 *                   &lt;element name="podnosilac_pronalazac" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podaci_o_pronalazacu"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="pronalazac_naveden" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="pronalazac" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
 *                             &lt;element name="lokacija" type="{}TAdresa_drzava"/&gt;
 *                             &lt;element name="kontakt" type="{}TKontakt_faks"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="punomocnik"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="funkcija"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="punomocnik_zastupanje" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="punomocnik_prijem_pismena" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="zajednicki_predstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;choice minOccurs="0"&gt;
 *                     &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
 *                     &lt;element name="poslovno_ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;/choice&gt;
 *                   &lt;element name="adresa" type="{}TAdresa" minOccurs="0"/&gt;
 *                   &lt;element name="kontakt" type="{}TKontakt" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="adresa_za_dostavljanje" type="{}TAdresa" minOccurs="0"/&gt;
 *         &lt;element name="nacin_dostavljanja"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="elektronski" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="papirno" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dopuna"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="dopunska_prijava" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                     &lt;element name="izdvojena_prijava" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="broj_osnovne_prijave" type="{}TBroj_prijave" minOccurs="0"/&gt;
 *                   &lt;element name="datum_osnovne_prijave" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="priznanje_prava_prvenstva_iz_ranijih_prijava"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence minOccurs="0"&gt;
 *                   &lt;element name="detalji_ranije_prijave" type="{}TDetalji_ranije_prijave" maxOccurs="5"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciZavod",
    "nazivPronalaska",
    "podnosilacPrijave",
    "podaciOPronalazacu",
    "punomocnik",
    "adresaZaDostavljanje",
    "nacinDostavljanja",
    "dopuna",
    "priznanjePravaPrvenstvaIzRanijihPrijava"
})
@XmlRootElement(name = "zahtev_za_priznanje_patenta")
public class ZahtevZaPriznanjePatenta {

    @XmlElement(name = "podaci_zavod", required = true)
    protected ZahtevZaPriznanjePatenta.PodaciZavod podaciZavod;
    @XmlElement(name = "naziv_pronalaska", required = true)
    protected ZahtevZaPriznanjePatenta.NazivPronalaska nazivPronalaska;
    @XmlElement(name = "podnosilac_prijave", required = true)
    protected ZahtevZaPriznanjePatenta.PodnosilacPrijave podnosilacPrijave;
    @XmlElement(name = "podaci_o_pronalazacu", required = true)
    protected ZahtevZaPriznanjePatenta.PodaciOPronalazacu podaciOPronalazacu;
    @XmlElement(required = true)
    protected ZahtevZaPriznanjePatenta.Punomocnik punomocnik;
    @XmlElement(name = "adresa_za_dostavljanje")
    protected TAdresa adresaZaDostavljanje;
    @XmlElement(name = "nacin_dostavljanja", required = true)
    protected ZahtevZaPriznanjePatenta.NacinDostavljanja nacinDostavljanja;
    @XmlElement(required = true)
    protected ZahtevZaPriznanjePatenta.Dopuna dopuna;
    @XmlElement(name = "priznanje_prava_prvenstva_iz_ranijih_prijava", required = true)
    protected ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava priznanjePravaPrvenstvaIzRanijihPrijava;
    
    /**
     * Gets the value of the podaciZavod property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.PodaciZavod }
     *     
     */
    public ZahtevZaPriznanjePatenta.PodaciZavod getPodaciZavod() {
        return podaciZavod;
    }

    /**
     * Sets the value of the podaciZavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.PodaciZavod }
     *     
     */
    public void setPodaciZavod(ZahtevZaPriznanjePatenta.PodaciZavod value) {
        this.podaciZavod = value;
    }

    /**
     * Gets the value of the nazivPronalaska property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.NazivPronalaska }
     *     
     */
    public ZahtevZaPriznanjePatenta.NazivPronalaska getNazivPronalaska() {
        return nazivPronalaska;
    }

    /**
     * Sets the value of the nazivPronalaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.NazivPronalaska }
     *     
     */
    public void setNazivPronalaska(ZahtevZaPriznanjePatenta.NazivPronalaska value) {
        this.nazivPronalaska = value;
    }

    /**
     * Gets the value of the podnosilacPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.PodnosilacPrijave }
     *     
     */
    public ZahtevZaPriznanjePatenta.PodnosilacPrijave getPodnosilacPrijave() {
        return podnosilacPrijave;
    }

    /**
     * Sets the value of the podnosilacPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.PodnosilacPrijave }
     *     
     */
    public void setPodnosilacPrijave(ZahtevZaPriznanjePatenta.PodnosilacPrijave value) {
        this.podnosilacPrijave = value;
    }

    /**
     * Gets the value of the podaciOPronalazacu property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu }
     *     
     */
    public ZahtevZaPriznanjePatenta.PodaciOPronalazacu getPodaciOPronalazacu() {
        return podaciOPronalazacu;
    }

    /**
     * Sets the value of the podaciOPronalazacu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu }
     *     
     */
    public void setPodaciOPronalazacu(ZahtevZaPriznanjePatenta.PodaciOPronalazacu value) {
        this.podaciOPronalazacu = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.Punomocnik }
     *     
     */
    public ZahtevZaPriznanjePatenta.Punomocnik getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.Punomocnik }
     *     
     */
    public void setPunomocnik(ZahtevZaPriznanjePatenta.Punomocnik value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the adresaZaDostavljanje property.
     * 
     * @return
     *     possible object is
     *     {@link TAdresa }
     *     
     */
    public TAdresa getAdresaZaDostavljanje() {
        return adresaZaDostavljanje;
    }

    /**
     * Sets the value of the adresaZaDostavljanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdresa }
     *     
     */
    public void setAdresaZaDostavljanje(TAdresa value) {
        this.adresaZaDostavljanje = value;
    }

    /**
     * Gets the value of the nacinDostavljanja property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.NacinDostavljanja }
     *     
     */
    public ZahtevZaPriznanjePatenta.NacinDostavljanja getNacinDostavljanja() {
        return nacinDostavljanja;
    }

    /**
     * Sets the value of the nacinDostavljanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.NacinDostavljanja }
     *     
     */
    public void setNacinDostavljanja(ZahtevZaPriznanjePatenta.NacinDostavljanja value) {
        this.nacinDostavljanja = value;
    }

    /**
     * Gets the value of the dopuna property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.Dopuna }
     *     
     */
    public ZahtevZaPriznanjePatenta.Dopuna getDopuna() {
        return dopuna;
    }

    /**
     * Sets the value of the dopuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.Dopuna }
     *     
     */
    public void setDopuna(ZahtevZaPriznanjePatenta.Dopuna value) {
        this.dopuna = value;
    }

    /**
     * Gets the value of the priznanjePravaPrvenstvaIzRanijihPrijava property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava }
     *     
     */
    public ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava getPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return priznanjePravaPrvenstvaIzRanijihPrijava;
    }

    /**
     * Sets the value of the priznanjePravaPrvenstvaIzRanijihPrijava property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava }
     *     
     */
    public void setPriznanjePravaPrvenstvaIzRanijihPrijava(ZahtevZaPriznanjePatenta.PriznanjePravaPrvenstvaIzRanijihPrijava value) {
        this.priznanjePravaPrvenstvaIzRanijihPrijava = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="dopunska_prijava" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *           &lt;element name="izdvojena_prijava" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="broj_osnovne_prijave" type="{}TBroj_prijave" minOccurs="0"/&gt;
     *         &lt;element name="datum_osnovne_prijave" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dopunskaPrijava",
        "izdvojenaPrijava",
        "brojOsnovnePrijave",
        "datumOsnovnePrijave"
    })
    public static class Dopuna {

        @XmlElement(name = "dopunska_prijava")
        protected boolean dopunskaPrijava;
        @XmlElement(name = "izdvojena_prijava")
        protected boolean izdvojenaPrijava;
        @XmlElement(name = "broj_osnovne_prijave")
        protected String brojOsnovnePrijave;
        @XmlElement(name = "datum_osnovne_prijave")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumOsnovnePrijave;

        /**
         * Gets the value of the dopunskaPrijava property.
         * 
         */
        public boolean isDopunskaPrijava() {
            return dopunskaPrijava;
        }

        /**
         * Sets the value of the dopunskaPrijava property.
         * 
         */
        public void setDopunskaPrijava(boolean value) {
            this.dopunskaPrijava = value;
        }

        /**
         * Gets the value of the izdvojenaPrijava property.
         * 
         */
        public boolean isIzdvojenaPrijava() {
            return izdvojenaPrijava;
        }

        /**
         * Sets the value of the izdvojenaPrijava property.
         * 
         */
        public void setIzdvojenaPrijava(boolean value) {
            this.izdvojenaPrijava = value;
        }

        /**
         * Gets the value of the brojOsnovnePrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojOsnovnePrijave() {
            return brojOsnovnePrijave;
        }

        /**
         * Sets the value of the brojOsnovnePrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojOsnovnePrijave(String value) {
            this.brojOsnovnePrijave = value;
        }

        /**
         * Gets the value of the datumOsnovnePrijave property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumOsnovnePrijave() {
            return datumOsnovnePrijave;
        }

        /**
         * Sets the value of the datumOsnovnePrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumOsnovnePrijave(XMLGregorianCalendar value) {
            this.datumOsnovnePrijave = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="elektronski" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="papirno" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elektronski",
        "papirno"
    })
    public static class NacinDostavljanja {

        @XmlElement(defaultValue = "false")
        protected boolean elektronski;
        protected boolean papirno;

        /**
         * Gets the value of the elektronski property.
         * 
         */
        public boolean isElektronski() {
            return elektronski;
        }

        /**
         * Sets the value of the elektronski property.
         * 
         */
        public void setElektronski(boolean value) {
            this.elektronski = value;
        }

        /**
         * Gets the value of the papirno property.
         * 
         */
        public boolean isPapirno() {
            return papirno;
        }

        /**
         * Sets the value of the papirno property.
         * 
         */
        public void setPapirno(boolean value) {
            this.papirno = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="naziv" type="{}TNaziv" maxOccurs="2" minOccurs="2"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv"
    })
    public static class NazivPronalaska {

        @XmlElement(required = true)
        protected List<TNaziv> naziv;

        /**
         * Gets the value of the naziv property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the naziv property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNaziv().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TNaziv }
         * 
         * 
         */
        public NazivPronalaska() {
        	this.naziv = new ArrayList<TNaziv>();
        }
        
        public List<TNaziv> getNaziv() {
            if (naziv == null) {
                naziv = new ArrayList<TNaziv>();
            }
            return this.naziv;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="pronalazac_naveden" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="pronalazac" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
     *                   &lt;element name="lokacija" type="{}TAdresa_drzava"/&gt;
     *                   &lt;element name="kontakt" type="{}TKontakt_faks"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pronalazacNaveden",
        "pronalazac"
    })
    public static class PodaciOPronalazacu {

        @XmlElement(name = "pronalazac_naveden")
        protected boolean pronalazacNaveden;
        protected ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac pronalazac;

        /**
         * Gets the value of the pronalazacNaveden property.
         * 
         */
        public boolean isPronalazacNaveden() {
            return pronalazacNaveden;
        }

        /**
         * Sets the value of the pronalazacNaveden property.
         * 
         */
        public void setPronalazacNaveden(boolean value) {
            this.pronalazacNaveden = value;
        }

        /**
         * Gets the value of the pronalazac property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac }
         *     
         */
        public ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac getPronalazac() {
            return pronalazac;
        }

        /**
         * Sets the value of the pronalazac property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac }
         *     
         */
        public void setPronalazac(ZahtevZaPriznanjePatenta.PodaciOPronalazacu.Pronalazac value) {
            this.pronalazac = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
         *         &lt;element name="lokacija" type="{}TAdresa_drzava"/&gt;
         *         &lt;element name="kontakt" type="{}TKontakt_faks"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fizickoLice",
            "lokacija",
            "kontakt"
        })
        public static class Pronalazac {

            @XmlElement(name = "fizicko_lice", required = true)
            protected TFizickoLice fizickoLice;
            @XmlElement(required = true)
            protected TAdresaDrzava lokacija;
            @XmlElement(required = true)
            protected TKontaktFaks kontakt;

            /**
             * Gets the value of the fizickoLice property.
             * 
             * @return
             *     possible object is
             *     {@link TFizickoLice }
             *     
             */
            public TFizickoLice getFizickoLice() {
                return fizickoLice;
            }

            /**
             * Sets the value of the fizickoLice property.
             * 
             * @param value
             *     allowed object is
             *     {@link TFizickoLice }
             *     
             */
            public void setFizickoLice(TFizickoLice value) {
                this.fizickoLice = value;
            }

            /**
             * Gets the value of the lokacija property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresaDrzava }
             *     
             */
            public TAdresaDrzava getLokacija() {
                return lokacija;
            }

            /**
             * Sets the value of the lokacija property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresaDrzava }
             *     
             */
            public void setLokacija(TAdresaDrzava value) {
                this.lokacija = value;
            }

            /**
             * Gets the value of the kontakt property.
             * 
             * @return
             *     possible object is
             *     {@link TKontaktFaks }
             *     
             */
            public TKontaktFaks getKontakt() {
                return kontakt;
            }

            /**
             * Sets the value of the kontakt property.
             * 
             * @param value
             *     allowed object is
             *     {@link TKontaktFaks }
             *     
             */
            public void setKontakt(TKontaktFaks value) {
                this.kontakt = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="broj_prijave" type="{}TBroj_prijave"/&gt;
     *         &lt;element name="datum_prijema" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPrijave",
        "datumPrijema",
        "datumPodnosenja",
        "statusZahteva",
        "sluzbenik",
        "obrazlozenje"
    })
    public static class PodaciZavod {

        @XmlElement(name = "broj_prijave", required = true)
        protected String brojPrijave;
        @XmlElement(name = "datum_prijema", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrijema;
        @XmlElement(name = "datum_podnosenja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPodnosenja;
        @XmlElement(name = "status_zahteva")
        protected String statusZahteva;
        @XmlElement(name = "sluzbenik")
        protected String sluzbenik;
        @XmlElement(name = "obrazlozenje")
        protected String obrazlozenje;
        
        public String getStatusZahteva() {
			return statusZahteva;
		}

		public void setStatusZahteva(String statusZahteva) {
			this.statusZahteva = statusZahteva;
		}

		public String getSluzbenik() {
			return sluzbenik;
		}

		public void setSluzbenik(String sluzbenik) {
			this.sluzbenik = sluzbenik;
		}

		public String getObrazlozenje() {
			return obrazlozenje;
		}

		public void setObrazlozenje(String obrazlozenje) {
			this.obrazlozenje = obrazlozenje;
		}

		/**
         * Gets the value of the brojPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijave() {
            return brojPrijave;
        }

        /**
         * Sets the value of the brojPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijave(String value) {
            this.brojPrijave = value;
        }

        /**
         * Gets the value of the datumPrijema property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrijema() {
            return datumPrijema;
        }

        /**
         * Sets the value of the datumPrijema property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrijema(XMLGregorianCalendar value) {
            this.datumPrijema = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPodnosenja(XMLGregorianCalendar value) {
            this.datumPodnosenja = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;choice&gt;
     *           &lt;sequence&gt;
     *             &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
     *             &lt;element name="drzavljanstvno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *           &lt;/sequence&gt;
     *           &lt;element name="poslovno_ime" type="{}TVelika_slova"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element name="lokacija" type="{}TAdresa_drzava"/&gt;
     *         &lt;element name="kontakt" type="{}TKontakt_faks"/&gt;
     *         &lt;element name="podnosilac_pronalazac" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fizickoLice",
        "drzavljanstvno",
        "poslovnoIme",
        "lokacija",
        "kontakt",
        "podnosilacPronalazac"
    })
    public static class PodnosilacPrijave {

        @XmlElement(name = "fizicko_lice")
        protected TFizickoLice fizickoLice;
        protected String drzavljanstvno;
        @XmlElement(name = "poslovno_ime")
        protected String poslovnoIme;
        @XmlElement(required = true)
        protected TAdresaDrzava lokacija;
        @XmlElement(required = true)
        protected TKontaktFaks kontakt;
        @XmlElement(name = "podnosilac_pronalazac", defaultValue = "false")
        protected boolean podnosilacPronalazac;

        /**
         * Gets the value of the fizickoLice property.
         * 
         * @return
         *     possible object is
         *     {@link TFizickoLice }
         *     
         */
        public TFizickoLice getFizickoLice() {
            return fizickoLice;
        }

        /**
         * Sets the value of the fizickoLice property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFizickoLice }
         *     
         */
        public void setFizickoLice(TFizickoLice value) {
            this.fizickoLice = value;
        }

        /**
         * Gets the value of the drzavljanstvno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrzavljanstvno() {
            return drzavljanstvno;
        }

        /**
         * Sets the value of the drzavljanstvno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrzavljanstvno(String value) {
            this.drzavljanstvno = value;
        }

        /**
         * Gets the value of the poslovnoIme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoslovnoIme() {
            return poslovnoIme;
        }

        /**
         * Sets the value of the poslovnoIme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoslovnoIme(String value) {
            this.poslovnoIme = value;
        }

        /**
         * Gets the value of the lokacija property.
         * 
         * @return
         *     possible object is
         *     {@link TAdresaDrzava }
         *     
         */
        public TAdresaDrzava getLokacija() {
            return lokacija;
        }

        /**
         * Sets the value of the lokacija property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAdresaDrzava }
         *     
         */
        public void setLokacija(TAdresaDrzava value) {
            this.lokacija = value;
        }

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link TKontaktFaks }
         *     
         */
        public TKontaktFaks getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link TKontaktFaks }
         *     
         */
        public void setKontakt(TKontaktFaks value) {
            this.kontakt = value;
        }

        /**
         * Gets the value of the podnosilacPronalazac property.
         * 
         */
        public boolean isPodnosilacPronalazac() {
            return podnosilacPronalazac;
        }

        /**
         * Sets the value of the podnosilacPronalazac property.
         * 
         */
        public void setPodnosilacPronalazac(boolean value) {
            this.podnosilacPronalazac = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence minOccurs="0"&gt;
     *         &lt;element name="detalji_ranije_prijave" type="{}TDetalji_ranije_prijave" maxOccurs="5"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "detaljiRanijePrijave"
    })
    public static class PriznanjePravaPrvenstvaIzRanijihPrijava {

        @XmlElement(name = "detalji_ranije_prijave")
        protected List<TDetaljiRanijePrijave> detaljiRanijePrijave;

        /**
         * Gets the value of the detaljiRanijePrijave property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the detaljiRanijePrijave property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDetaljiRanijePrijave().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TDetaljiRanijePrijave }
         * 
         * 
         */
        public PriznanjePravaPrvenstvaIzRanijihPrijava() {
        	this.detaljiRanijePrijave = new ArrayList<TDetaljiRanijePrijave>();
        }
        
        public List<TDetaljiRanijePrijave> getDetaljiRanijePrijave() {
            if (detaljiRanijePrijave == null) {
                detaljiRanijePrijave = new ArrayList<TDetaljiRanijePrijave>();
            }
            return this.detaljiRanijePrijave;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="funkcija"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="punomocnik_zastupanje" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="punomocnik_prijem_pismena" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="zajednicki_predstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;choice minOccurs="0"&gt;
     *           &lt;element name="fizicko_lice" type="{}TFizicko_lice"/&gt;
     *           &lt;element name="poslovno_ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element name="adresa" type="{}TAdresa" minOccurs="0"/&gt;
     *         &lt;element name="kontakt" type="{}TKontakt" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "funkcija",
        "fizickoLice",
        "poslovnoIme",
        "adresa",
        "kontakt"
    })
    public static class Punomocnik {

        @XmlElement(required = true)
        protected ZahtevZaPriznanjePatenta.Punomocnik.Funkcija funkcija;
        @XmlElement(name = "fizicko_lice")
        protected TFizickoLice fizickoLice;
        @XmlElement(name = "poslovno_ime")
        protected String poslovnoIme;
        protected TAdresa adresa;
        protected TKontakt kontakt;

        /**
         * Gets the value of the funkcija property.
         * 
         * @return
         *     possible object is
         *     {@link ZahtevZaPriznanjePatenta.Punomocnik.Funkcija }
         *     
         */
        public ZahtevZaPriznanjePatenta.Punomocnik.Funkcija getFunkcija() {
            return funkcija;
        }

        /**
         * Sets the value of the funkcija property.
         * 
         * @param value
         *     allowed object is
         *     {@link ZahtevZaPriznanjePatenta.Punomocnik.Funkcija }
         *     
         */
        public void setFunkcija(ZahtevZaPriznanjePatenta.Punomocnik.Funkcija value) {
            this.funkcija = value;
        }

        /**
         * Gets the value of the fizickoLice property.
         * 
         * @return
         *     possible object is
         *     {@link TFizickoLice }
         *     
         */
        public TFizickoLice getFizickoLice() {
            return fizickoLice;
        }

        /**
         * Sets the value of the fizickoLice property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFizickoLice }
         *     
         */
        public void setFizickoLice(TFizickoLice value) {
            this.fizickoLice = value;
        }

        /**
         * Gets the value of the poslovnoIme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoslovnoIme() {
            return poslovnoIme;
        }

        /**
         * Sets the value of the poslovnoIme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoslovnoIme(String value) {
            this.poslovnoIme = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link TAdresa }
         *     
         */
        public TAdresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAdresa }
         *     
         */
        public void setAdresa(TAdresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link TKontakt }
         *     
         */
        public TKontakt getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link TKontakt }
         *     
         */
        public void setKontakt(TKontakt value) {
            this.kontakt = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="punomocnik_zastupanje" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="punomocnik_prijem_pismena" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="zajednicki_predstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "punomocnikZastupanje",
            "punomocnikPrijemPismena",
            "zajednickiPredstavnik"
        })
        public static class Funkcija {

            @XmlElement(name = "punomocnik_zastupanje")
            protected boolean punomocnikZastupanje;
            @XmlElement(name = "punomocnik_prijem_pismena")
            protected boolean punomocnikPrijemPismena;
            @XmlElement(name = "zajednicki_predstavnik")
            protected boolean zajednickiPredstavnik;

            /**
             * Gets the value of the punomocnikZastupanje property.
             * 
             */
            public boolean isPunomocnikZastupanje() {
                return punomocnikZastupanje;
            }

            /**
             * Sets the value of the punomocnikZastupanje property.
             * 
             */
            public void setPunomocnikZastupanje(boolean value) {
                this.punomocnikZastupanje = value;
            }

            /**
             * Gets the value of the punomocnikPrijemPismena property.
             * 
             */
            public boolean isPunomocnikPrijemPismena() {
                return punomocnikPrijemPismena;
            }

            /**
             * Sets the value of the punomocnikPrijemPismena property.
             * 
             */
            public void setPunomocnikPrijemPismena(boolean value) {
                this.punomocnikPrijemPismena = value;
            }

            /**
             * Gets the value of the zajednickiPredstavnik property.
             * 
             */
            public boolean isZajednickiPredstavnik() {
                return zajednickiPredstavnik;
            }

            /**
             * Sets the value of the zajednickiPredstavnik property.
             * 
             */
            public void setZajednickiPredstavnik(boolean value) {
                this.zajednickiPredstavnik = value;
            }

        }

    }

}
