//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.12 at 09:29:15 PM GMT+01:00 
//


package main.java.com.xws.a1document.xml.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the a_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: a_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObrazacA1 }
     * 
     */
    public ObrazacA1 createObrazacA1() {
        return new ObrazacA1();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev }
     * 
     */
    public ObrazacA1 .Zahtev createObrazacA1Zahtev() {
        return new ObrazacA1 .Zahtev();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.NaslovAutorskogDela }
     * 
     */
    public ObrazacA1 .Zahtev.NaslovAutorskogDela createObrazacA1ZahtevNaslovAutorskogDela() {
        return new ObrazacA1 .Zahtev.NaslovAutorskogDela();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zavod }
     * 
     */
    public ObrazacA1 .Zavod createObrazacA1Zavod() {
        return new ObrazacA1 .Zavod();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TAutor }
     * 
     */
    public TAutor createTAutor() {
        return new TAutor();
    }

    /**
     * Create an instance of {@link TAutorZiv }
     * 
     */
    public TAutorZiv createTAutorZiv() {
        return new TAutorZiv();
    }

    /**
     * Create an instance of {@link TAutorPreminuo }
     * 
     */
    public TAutorPreminuo createTAutorPreminuo() {
        return new TAutorPreminuo();
    }

    /**
     * Create an instance of {@link TPravnoLice.Sediste }
     * 
     */
    public TPravnoLice.Sediste createTPravnoLiceSediste() {
        return new TPravnoLice.Sediste();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.Podnosilac }
     * 
     */
    public ObrazacA1 .Zahtev.Podnosilac createObrazacA1ZahtevPodnosilac() {
        return new ObrazacA1 .Zahtev.Podnosilac();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.PseudonimZnakAutora }
     * 
     */
    public ObrazacA1 .Zahtev.PseudonimZnakAutora createObrazacA1ZahtevPseudonimZnakAutora() {
        return new ObrazacA1 .Zahtev.PseudonimZnakAutora();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.Punomocnik }
     * 
     */
    public ObrazacA1 .Zahtev.Punomocnik createObrazacA1ZahtevPunomocnik() {
        return new ObrazacA1 .Zahtev.Punomocnik();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.NaslovDeloPrerade }
     * 
     */
    public ObrazacA1 .Zahtev.NaslovDeloPrerade createObrazacA1ZahtevNaslovDeloPrerade() {
        return new ObrazacA1 .Zahtev.NaslovDeloPrerade();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.VrstaAutorskogDela }
     * 
     */
    public ObrazacA1 .Zahtev.VrstaAutorskogDela createObrazacA1ZahtevVrstaAutorskogDela() {
        return new ObrazacA1 .Zahtev.VrstaAutorskogDela();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.FormaZapisaAutorskogDela }
     * 
     */
    public ObrazacA1 .Zahtev.FormaZapisaAutorskogDela createObrazacA1ZahtevFormaZapisaAutorskogDela() {
        return new ObrazacA1 .Zahtev.FormaZapisaAutorskogDela();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac }
     * 
     */
    public ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac createObrazacA1ZahtevPodaciOAutoruNepodnosilac() {
        return new ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom }
     * 
     */
    public ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom createObrazacA1ZahtevAutorskoDeloStvorenoRadnimOdnosom() {
        return new ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.NacinKoriscenja }
     * 
     */
    public ObrazacA1 .Zahtev.NacinKoriscenja createObrazacA1ZahtevNacinKoriscenja() {
        return new ObrazacA1 .Zahtev.NacinKoriscenja();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.Prilozi }
     * 
     */
    public ObrazacA1 .Zahtev.Prilozi createObrazacA1ZahtevPrilozi() {
        return new ObrazacA1 .Zahtev.Prilozi();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.BrojPrijave }
     * 
     */
    public ObrazacA1 .Zahtev.BrojPrijave createObrazacA1ZahtevBrojPrijave() {
        return new ObrazacA1 .Zahtev.BrojPrijave();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.DatumPodnosenja }
     * 
     */
    public ObrazacA1 .Zahtev.DatumPodnosenja createObrazacA1ZahtevDatumPodnosenja() {
        return new ObrazacA1 .Zahtev.DatumPodnosenja();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov }
     * 
     */
    public ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov createObrazacA1ZahtevNaslovAutorskogDelaNaslov() {
        return new ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov();
    }

    /**
     * Create an instance of {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov }
     * 
     */
    public ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov createObrazacA1ZahtevNaslovAutorskogDelaAlternativniNaslov() {
        return new ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov();
    }

}
