//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.12 at 09:29:15 PM GMT+01:00 
//


package main.java.com.xws.a1document.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zavod",
    "zahtev"
})
@XmlRootElement(name = "obrazac_a_1")
public class ObrazacA1 {

    @XmlElement(required = true)
    protected ObrazacA1 .Zavod zavod;
    @XmlElement(required = true)
    protected ObrazacA1 .Zahtev zahtev;

    public ObrazacA1 .Zavod getZavod() {
        return zavod;
    }

    public void setZavod(ObrazacA1 .Zavod value) {
        this.zavod = value;
    }

    public ObrazacA1 .Zahtev getZahtev() {
        return zahtev;
    }

    public void setZahtev(ObrazacA1 .Zahtev value) {
        this.zahtev = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilac",
        "pseudonimZnakAutora",
        "punomocnik",
        "naslovAutorskogDela",
        "naslovDeloPrerade",
        "vrstaAutorskogDela",
        "formaZapisaAutorskogDela",
        "podaciOAutoruNepodnosilac",
        "autorskoDeloStvorenoRadnimOdnosom",
        "nacinKoriscenja",
        "prilozi",
        "brojPrijave",
        "datumPodnosenja"
    })
    public static class Zahtev {

        @XmlElement(required = true)
        protected ObrazacA1 .Zahtev.Podnosilac podnosilac;
        @XmlElement(name = "pseudonim_znak_autora", required = true)
        protected ObrazacA1 .Zahtev.PseudonimZnakAutora pseudonimZnakAutora;
        @XmlElement(required = true)
        protected ObrazacA1 .Zahtev.Punomocnik punomocnik;
        @XmlElement(name = "naslov_autorskog_dela", required = true)
        protected ObrazacA1 .Zahtev.NaslovAutorskogDela naslovAutorskogDela;
        @XmlElement(name = "naslov_delo_prerade", required = true)
        protected ObrazacA1 .Zahtev.NaslovDeloPrerade naslovDeloPrerade;
        @XmlElement(name = "vrsta_autorskog_dela", required = true)
        protected ObrazacA1 .Zahtev.VrstaAutorskogDela vrstaAutorskogDela;
        @XmlElement(name = "forma_zapisa_autorskog_dela", required = true)
        protected ObrazacA1 .Zahtev.FormaZapisaAutorskogDela formaZapisaAutorskogDela;
        @XmlElement(name = "podaci_o_autoru_nepodnosilac", required = true)
        protected ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac podaciOAutoruNepodnosilac;
        @XmlElement(name = "autorsko_delo_stvoreno_radnim_odnosom", required = true)
        protected ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom autorskoDeloStvorenoRadnimOdnosom;
        @XmlElement(name = "nacin_koriscenja", required = true)
        protected ObrazacA1 .Zahtev.NacinKoriscenja nacinKoriscenja;
        @XmlElement(required = true)
        protected ObrazacA1 .Zahtev.Prilozi prilozi;
        @XmlElement(name = "broj_prijave", required = true)
        protected ObrazacA1 .Zahtev.BrojPrijave brojPrijave;
        @XmlElement(name = "datum_podnosenja", required = true)
        protected ObrazacA1 .Zahtev.DatumPodnosenja datumPodnosenja;
        @XmlAttribute(name = "naslov")
        @XmlSchemaType(name = "anySimpleType")
        protected String naslov;
        @XmlAttribute(name = "status")
        @XmlSchemaType(name = "anySimpleType")
        protected String status;        
        @XmlAttribute(name = "datobrade")
        @XmlSchemaType(name = "anySimpleType")
        protected String datumObrade;
        @XmlAttribute(name = "ime")
        @XmlSchemaType(name = "anySimpleType")
        protected String ime;
        @XmlAttribute(name = "prezime")
        @XmlSchemaType(name = "anySimpleType")
        protected String prezime;
        @XmlAttribute(name = "obrazlozenje")
        @XmlSchemaType(name = "anySimpleType")
        protected String obrazlozenje;
        
        public String getDatumObrade() {
			return datumObrade;
		}

		public void setDatumObrade(String datumObrade) {
			this.datumObrade = datumObrade;
		}

		public String getIme() {
			return ime;
		}

		public void setIme(String ime) {
			this.ime = ime;
		}

		public String getPrezime() {
			return prezime;
		}

		public void setPrezime(String prezime) {
			this.prezime = prezime;
		}

		public String getObrazlozenje() {
			return obrazlozenje;
		}

		public void setObrazlozenje(String obrazlozenje) {
			this.obrazlozenje = obrazlozenje;
		}

		public String getStatus() {
			return status;
		}

		public void setStatus(String status) {
			this.status = status;
		}

		public ObrazacA1 .Zahtev.Podnosilac getPodnosilac() {
            return podnosilac;
        }

        public void setPodnosilac(ObrazacA1 .Zahtev.Podnosilac value) {
            this.podnosilac = value;
        }

        public ObrazacA1 .Zahtev.PseudonimZnakAutora getPseudonimZnakAutora() {
            return pseudonimZnakAutora;
        }

        public void setPseudonimZnakAutora(ObrazacA1 .Zahtev.PseudonimZnakAutora value) {
            this.pseudonimZnakAutora = value;
        }

        public ObrazacA1 .Zahtev.Punomocnik getPunomocnik() {
            return punomocnik;
        }

        public void setPunomocnik(ObrazacA1 .Zahtev.Punomocnik value) {
            this.punomocnik = value;
        }

        public ObrazacA1 .Zahtev.NaslovAutorskogDela getNaslovAutorskogDela() {
            return naslovAutorskogDela;
        }

        public void setNaslovAutorskogDela(ObrazacA1 .Zahtev.NaslovAutorskogDela value) {
            this.naslovAutorskogDela = value;
        }

        public ObrazacA1 .Zahtev.NaslovDeloPrerade getNaslovDeloPrerade() {
            return naslovDeloPrerade;
        }

        public void setNaslovDeloPrerade(ObrazacA1 .Zahtev.NaslovDeloPrerade value) {
            this.naslovDeloPrerade = value;
        }

        public ObrazacA1 .Zahtev.VrstaAutorskogDela getVrstaAutorskogDela() {
            return vrstaAutorskogDela;
        }

        public void setVrstaAutorskogDela(ObrazacA1 .Zahtev.VrstaAutorskogDela value) {
            this.vrstaAutorskogDela = value;
        }

        public ObrazacA1 .Zahtev.FormaZapisaAutorskogDela getFormaZapisaAutorskogDela() {
            return formaZapisaAutorskogDela;
        }

        public void setFormaZapisaAutorskogDela(ObrazacA1 .Zahtev.FormaZapisaAutorskogDela value) {
            this.formaZapisaAutorskogDela = value;
        }

        public ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac getPodaciOAutoruNepodnosilac() {
            return podaciOAutoruNepodnosilac;
        }

        public void setPodaciOAutoruNepodnosilac(ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac value) {
            this.podaciOAutoruNepodnosilac = value;
        }

        public ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom getAutorskoDeloStvorenoRadnimOdnosom() {
            return autorskoDeloStvorenoRadnimOdnosom;
        }

        public void setAutorskoDeloStvorenoRadnimOdnosom(ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom value) {
            this.autorskoDeloStvorenoRadnimOdnosom = value;
        }

        public ObrazacA1 .Zahtev.NacinKoriscenja getNacinKoriscenja() {
            return nacinKoriscenja;
        }

        public void setNacinKoriscenja(ObrazacA1 .Zahtev.NacinKoriscenja value) {
            this.nacinKoriscenja = value;
        }

        public ObrazacA1 .Zahtev.Prilozi getPrilozi() {
            return prilozi;
        }

        public void setPrilozi(ObrazacA1 .Zahtev.Prilozi value) {
            this.prilozi = value;
        }

        public ObrazacA1 .Zahtev.BrojPrijave getBrojPrijave() {
            return brojPrijave;
        }

        public void setBrojPrijave(ObrazacA1 .Zahtev.BrojPrijave value) {
            this.brojPrijave = value;
        }

        public ObrazacA1 .Zahtev.DatumPodnosenja getDatumPodnosenja() {
            return datumPodnosenja;
        }

        public void setDatumPodnosenja(ObrazacA1 .Zahtev.DatumPodnosenja value) {
            this.datumPodnosenja = value;
        }

        public String getNaslov() {
            return naslov;
        }

        public void setNaslov(String value) {
            this.naslov = value;
        }

        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AutorskoDeloStvorenoRadnimOdnosom {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BrojPrijave {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DatumPodnosenja {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


 
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class FormaZapisaAutorskogDela {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }



        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class NacinKoriscenja {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naslov",
            "alternativniNaslov"
        })
        public static class NaslovAutorskogDela {

            @XmlElement(required = true)
            protected ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov naslov;
            @XmlElement(name = "alternativni_naslov", required = true)
            protected ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov alternativniNaslov;

            /**
             * Gets the value of the naslov property.
             * 
             * @return
             *     possible object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov }
             *     
             */
            public ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov getNaslov() {
                return naslov;
            }

            /**
             * Sets the value of the naslov property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov }
             *     
             */
            public void setNaslov(ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov value) {
                this.naslov = value;
            }

            /**
             * Gets the value of the alternativniNaslov property.
             * 
             * @return
             *     possible object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov }
             *     
             */
            public ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov getAlternativniNaslov() {
                return alternativniNaslov;
            }

            /**
             * Sets the value of the alternativniNaslov property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov }
             *     
             */
            public void setAlternativniNaslov(ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov value) {
                this.alternativniNaslov = value;
            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class AlternativniNaslov {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "reuqired")
                @XmlSchemaType(name = "anySimpleType")
                protected String reuqired;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the reuqired property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReuqired() {
                    return reuqired;
                }

                /**
                 * Sets the value of the reuqired property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReuqired(String value) {
                    this.reuqired = value;
                }

            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Naslov {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "required")
                @XmlSchemaType(name = "anySimpleType")
                protected String required;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequired(String value) {
                    this.required = value;
                }

            }

        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naslov",
            "autor"
        })
        public static class NaslovDeloPrerade {

            @XmlElement(required = true)
            protected String naslov;
            @XmlElement(required = true)
            protected TAutor autor;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the naslov property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaslov() {
                return naslov;
            }

            /**
             * Sets the value of the naslov property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaslov(String value) {
                this.naslov = value;
            }

            /**
             * Gets the value of the autor property.
             * 
             * @return
             *     possible object is
             *     {@link TAutor }
             *     
             */
            public TAutor getAutor() {
                return autor;
            }

            /**
             * Sets the value of the autor property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAutor }
             *     
             */
            public void setAutor(TAutor value) {
                this.autor = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "autor"
        })
        public static class PodaciOAutoruNepodnosilac {

            @XmlElement(required = true)
            protected TAutor autor;
            //protected List<TAutor> autor;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the autor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the autor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TAutor }
             * 
             * 
             */
            public TAutor getAutor() {                
                return this.autor;
            }
            
            public void setAutor(TAutor value) {
            	this.autor = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lice"
        })
        public static class Podnosilac {

            @XmlElement(required = true)
            protected TLice lice;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the lice property.
             * 
             * @return
             *     possible object is
             *     {@link TLice }
             *     
             */
            public TLice getLice() {
                return lice;
            }

            /**
             * Sets the value of the lice property.
             * 
             * @param value
             *     allowed object is
             *     {@link TLice }
             *     
             */
            public void setLice(TLice value) {
                this.lice = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


 
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "opisAutorskogDela",
            "primerAutorskogDela"
        })
        public static class Prilozi {

            @XmlElement(name = "opis_autorskog_dela", required = true)
            protected String opisAutorskogDela;
            @XmlElement(name = "primer_autorskog_dela", required = true)
            protected String primerAutorskogDela;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the opisAutorskogDela property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOpisAutorskogDela() {
                return opisAutorskogDela;
            }

            /**
             * Sets the value of the opisAutorskogDela property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOpisAutorskogDela(String value) {
                this.opisAutorskogDela = value;
            }

            /**
             * Gets the value of the primerAutorskogDela property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimerAutorskogDela() {
                return primerAutorskogDela;
            }

            /**
             * Sets the value of the primerAutorskogDela property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimerAutorskogDela(String value) {
                this.primerAutorskogDela = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }

       
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class PseudonimZnakAutora {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


      
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "adresa"
        })
        public static class Punomocnik {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;
            @XmlElement(required = true)
            protected TAdresa adresa;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresa }
             *     
             */
            public TAdresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresa }
             *     
             */
            public void setAdresa(TAdresa value) {
                this.adresa = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class VrstaAutorskogDela {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "adresa"
    })
    public static class Zavod {

        @XmlElement(required = true)
        protected String naziv;
        @XmlElement(required = true)
        protected TAdresa adresa;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link TAdresa }
         *     
         */
        public TAdresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAdresa }
         *     
         */
        public void setAdresa(TAdresa value) {
            this.adresa = value;
        }

    }

}
