//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.12 at 09:29:15 PM GMT+01:00 
//


package main.java.com.xws.a1document.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zavod"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="adresa" type="{a-1}t-adresa"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="zahtev"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="podnosilac"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="lice" type="{a-1}t-lice"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="pseudonim-znak-autora"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="punomocnik"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="adresa" type="{a-1}t-adresa"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="naslov-autorskog-dela"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="naslov"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
 *                                     &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="alternativni-naslov"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
 *                                     &lt;attribute name="reuqired" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="naslov-delo-prerade"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="naslov" type="{a-1}tekst-naslov"/&gt;
 *                             &lt;element name="autor" type="{a-1}t-autor"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="vrsta-autorskog-dela"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="forma-zapisa-autorskog-dela"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="podaci-o-autoru-nepodnosilac"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="autor" type="{a-1}t-autor" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="autorsko-delo-stvoreno-radnim-odnosom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="nacin-koriscenja"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="prilozi"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="opis-autorskog-dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="primer-autorskog-dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="broj-prijave"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;a-1&gt;t-broj-prijave"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="datum-podnosenja"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;a-1&gt;t-datum-podnosenja"&gt;
 *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="naslov" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zavod",
    "zahtev"
})
@XmlRootElement(name = "obrazac-a-1")
public class ObrazacA1 {

    @XmlElement(required = true)
    protected ObrazacA1 .Zavod zavod;
    @XmlElement(required = true)
    protected ObrazacA1 .Zahtev zahtev;

    /**
     * Gets the value of the zavod property.
     * 
     * @return
     *     possible object is
     *     {@link ObrazacA1 .Zavod }
     *     
     */
    public ObrazacA1 .Zavod getZavod() {
        return zavod;
    }

    /**
     * Sets the value of the zavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObrazacA1 .Zavod }
     *     
     */
    public void setZavod(ObrazacA1 .Zavod value) {
        this.zavod = value;
    }

    /**
     * Gets the value of the zahtev property.
     * 
     * @return
     *     possible object is
     *     {@link ObrazacA1 .Zahtev }
     *     
     */
    public ObrazacA1 .Zahtev getZahtev() {
        return zahtev;
    }

    /**
     * Sets the value of the zahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObrazacA1 .Zahtev }
     *     
     */
    public void setZahtev(ObrazacA1 .Zahtev value) {
        this.zahtev = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="podnosilac"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="lice" type="{a-1}t-lice"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="pseudonim-znak-autora"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="punomocnik"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="adresa" type="{a-1}t-adresa"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="naslov-autorskog-dela"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="naslov"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
     *                           &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="alternativni-naslov"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
     *                           &lt;attribute name="reuqired" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="naslov-delo-prerade"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="naslov" type="{a-1}tekst-naslov"/&gt;
     *                   &lt;element name="autor" type="{a-1}t-autor"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="vrsta-autorskog-dela"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="forma-zapisa-autorskog-dela"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="podaci-o-autoru-nepodnosilac"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="autor" type="{a-1}t-autor" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="autorsko-delo-stvoreno-radnim-odnosom"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="nacin-koriscenja"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="prilozi"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="opis-autorskog-dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="primer-autorskog-dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="broj-prijave"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;a-1&gt;t-broj-prijave"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="datum-podnosenja"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;a-1&gt;t-datum-podnosenja"&gt;
     *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="naslov" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilac",
        "pseudonimZnakAutora",
        "punomocnik",
        "naslovAutorskogDela",
        "naslovDeloPrerade",
        "vrstaAutorskogDela",
        "formaZapisaAutorskogDela",
        "podaciOAutoruNepodnosilac",
        "autorskoDeloStvorenoRadnimOdnosom",
        "nacinKoriscenja",
        "prilozi",
        "brojPrijave",
        "datumPodnosenja"
    })
    public static class Zahtev {

        @XmlElement(required = true)
        protected ObrazacA1 .Zahtev.Podnosilac podnosilac;
        @XmlElement(name = "pseudonim-znak-autora", required = true)
        protected ObrazacA1 .Zahtev.PseudonimZnakAutora pseudonimZnakAutora;
        @XmlElement(required = true)
        protected ObrazacA1 .Zahtev.Punomocnik punomocnik;
        @XmlElement(name = "naslov-autorskog-dela", required = true)
        protected ObrazacA1 .Zahtev.NaslovAutorskogDela naslovAutorskogDela;
        @XmlElement(name = "naslov-delo-prerade", required = true)
        protected ObrazacA1 .Zahtev.NaslovDeloPrerade naslovDeloPrerade;
        @XmlElement(name = "vrsta-autorskog-dela", required = true)
        protected ObrazacA1 .Zahtev.VrstaAutorskogDela vrstaAutorskogDela;
        @XmlElement(name = "forma-zapisa-autorskog-dela", required = true)
        protected ObrazacA1 .Zahtev.FormaZapisaAutorskogDela formaZapisaAutorskogDela;
        @XmlElement(name = "podaci-o-autoru-nepodnosilac", required = true)
        protected ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac podaciOAutoruNepodnosilac;
        @XmlElement(name = "autorsko-delo-stvoreno-radnim-odnosom", required = true)
        protected ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom autorskoDeloStvorenoRadnimOdnosom;
        @XmlElement(name = "nacin-koriscenja", required = true)
        protected ObrazacA1 .Zahtev.NacinKoriscenja nacinKoriscenja;
        @XmlElement(required = true)
        protected ObrazacA1 .Zahtev.Prilozi prilozi;
        @XmlElement(name = "broj-prijave", required = true)
        protected ObrazacA1 .Zahtev.BrojPrijave brojPrijave;
        @XmlElement(name = "datum-podnosenja", required = true)
        protected ObrazacA1 .Zahtev.DatumPodnosenja datumPodnosenja;
        @XmlAttribute(name = "naslov")
        @XmlSchemaType(name = "anySimpleType")
        protected String naslov;

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.Podnosilac }
         *     
         */
        public ObrazacA1 .Zahtev.Podnosilac getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.Podnosilac }
         *     
         */
        public void setPodnosilac(ObrazacA1 .Zahtev.Podnosilac value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the pseudonimZnakAutora property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.PseudonimZnakAutora }
         *     
         */
        public ObrazacA1 .Zahtev.PseudonimZnakAutora getPseudonimZnakAutora() {
            return pseudonimZnakAutora;
        }

        /**
         * Sets the value of the pseudonimZnakAutora property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.PseudonimZnakAutora }
         *     
         */
        public void setPseudonimZnakAutora(ObrazacA1 .Zahtev.PseudonimZnakAutora value) {
            this.pseudonimZnakAutora = value;
        }

        /**
         * Gets the value of the punomocnik property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.Punomocnik }
         *     
         */
        public ObrazacA1 .Zahtev.Punomocnik getPunomocnik() {
            return punomocnik;
        }

        /**
         * Sets the value of the punomocnik property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.Punomocnik }
         *     
         */
        public void setPunomocnik(ObrazacA1 .Zahtev.Punomocnik value) {
            this.punomocnik = value;
        }

        /**
         * Gets the value of the naslovAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela }
         *     
         */
        public ObrazacA1 .Zahtev.NaslovAutorskogDela getNaslovAutorskogDela() {
            return naslovAutorskogDela;
        }

        /**
         * Sets the value of the naslovAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela }
         *     
         */
        public void setNaslovAutorskogDela(ObrazacA1 .Zahtev.NaslovAutorskogDela value) {
            this.naslovAutorskogDela = value;
        }

        /**
         * Gets the value of the naslovDeloPrerade property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.NaslovDeloPrerade }
         *     
         */
        public ObrazacA1 .Zahtev.NaslovDeloPrerade getNaslovDeloPrerade() {
            return naslovDeloPrerade;
        }

        /**
         * Sets the value of the naslovDeloPrerade property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.NaslovDeloPrerade }
         *     
         */
        public void setNaslovDeloPrerade(ObrazacA1 .Zahtev.NaslovDeloPrerade value) {
            this.naslovDeloPrerade = value;
        }

        /**
         * Gets the value of the vrstaAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.VrstaAutorskogDela }
         *     
         */
        public ObrazacA1 .Zahtev.VrstaAutorskogDela getVrstaAutorskogDela() {
            return vrstaAutorskogDela;
        }

        /**
         * Sets the value of the vrstaAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.VrstaAutorskogDela }
         *     
         */
        public void setVrstaAutorskogDela(ObrazacA1 .Zahtev.VrstaAutorskogDela value) {
            this.vrstaAutorskogDela = value;
        }

        /**
         * Gets the value of the formaZapisaAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.FormaZapisaAutorskogDela }
         *     
         */
        public ObrazacA1 .Zahtev.FormaZapisaAutorskogDela getFormaZapisaAutorskogDela() {
            return formaZapisaAutorskogDela;
        }

        /**
         * Sets the value of the formaZapisaAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.FormaZapisaAutorskogDela }
         *     
         */
        public void setFormaZapisaAutorskogDela(ObrazacA1 .Zahtev.FormaZapisaAutorskogDela value) {
            this.formaZapisaAutorskogDela = value;
        }

        /**
         * Gets the value of the podaciOAutoruNepodnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac }
         *     
         */
        public ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac getPodaciOAutoruNepodnosilac() {
            return podaciOAutoruNepodnosilac;
        }

        /**
         * Sets the value of the podaciOAutoruNepodnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac }
         *     
         */
        public void setPodaciOAutoruNepodnosilac(ObrazacA1 .Zahtev.PodaciOAutoruNepodnosilac value) {
            this.podaciOAutoruNepodnosilac = value;
        }

        /**
         * Gets the value of the autorskoDeloStvorenoRadnimOdnosom property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom }
         *     
         */
        public ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom getAutorskoDeloStvorenoRadnimOdnosom() {
            return autorskoDeloStvorenoRadnimOdnosom;
        }

        /**
         * Sets the value of the autorskoDeloStvorenoRadnimOdnosom property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom }
         *     
         */
        public void setAutorskoDeloStvorenoRadnimOdnosom(ObrazacA1 .Zahtev.AutorskoDeloStvorenoRadnimOdnosom value) {
            this.autorskoDeloStvorenoRadnimOdnosom = value;
        }

        /**
         * Gets the value of the nacinKoriscenja property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.NacinKoriscenja }
         *     
         */
        public ObrazacA1 .Zahtev.NacinKoriscenja getNacinKoriscenja() {
            return nacinKoriscenja;
        }

        /**
         * Sets the value of the nacinKoriscenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.NacinKoriscenja }
         *     
         */
        public void setNacinKoriscenja(ObrazacA1 .Zahtev.NacinKoriscenja value) {
            this.nacinKoriscenja = value;
        }

        /**
         * Gets the value of the prilozi property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.Prilozi }
         *     
         */
        public ObrazacA1 .Zahtev.Prilozi getPrilozi() {
            return prilozi;
        }

        /**
         * Sets the value of the prilozi property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.Prilozi }
         *     
         */
        public void setPrilozi(ObrazacA1 .Zahtev.Prilozi value) {
            this.prilozi = value;
        }

        /**
         * Gets the value of the brojPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.BrojPrijave }
         *     
         */
        public ObrazacA1 .Zahtev.BrojPrijave getBrojPrijave() {
            return brojPrijave;
        }

        /**
         * Sets the value of the brojPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.BrojPrijave }
         *     
         */
        public void setBrojPrijave(ObrazacA1 .Zahtev.BrojPrijave value) {
            this.brojPrijave = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link ObrazacA1 .Zahtev.DatumPodnosenja }
         *     
         */
        public ObrazacA1 .Zahtev.DatumPodnosenja getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link ObrazacA1 .Zahtev.DatumPodnosenja }
         *     
         */
        public void setDatumPodnosenja(ObrazacA1 .Zahtev.DatumPodnosenja value) {
            this.datumPodnosenja = value;
        }

        /**
         * Gets the value of the naslov property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AutorskoDeloStvorenoRadnimOdnosom {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;a-1&gt;t-broj-prijave"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BrojPrijave {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;a-1&gt;t-datum-podnosenja"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DatumPodnosenja {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class FormaZapisaAutorskogDela {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class NacinKoriscenja {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="naslov"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
         *                 &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="alternativni-naslov"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
         *                 &lt;attribute name="reuqired" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naslov",
            "alternativniNaslov"
        })
        public static class NaslovAutorskogDela {

            @XmlElement(required = true)
            protected ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov naslov;
            @XmlElement(name = "alternativni-naslov", required = true)
            protected ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov alternativniNaslov;

            /**
             * Gets the value of the naslov property.
             * 
             * @return
             *     possible object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov }
             *     
             */
            public ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov getNaslov() {
                return naslov;
            }

            /**
             * Sets the value of the naslov property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov }
             *     
             */
            public void setNaslov(ObrazacA1 .Zahtev.NaslovAutorskogDela.Naslov value) {
                this.naslov = value;
            }

            /**
             * Gets the value of the alternativniNaslov property.
             * 
             * @return
             *     possible object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov }
             *     
             */
            public ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov getAlternativniNaslov() {
                return alternativniNaslov;
            }

            /**
             * Sets the value of the alternativniNaslov property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov }
             *     
             */
            public void setAlternativniNaslov(ObrazacA1 .Zahtev.NaslovAutorskogDela.AlternativniNaslov value) {
                this.alternativniNaslov = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
             *       &lt;attribute name="reuqired" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class AlternativniNaslov {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "reuqired")
                @XmlSchemaType(name = "anySimpleType")
                protected String reuqired;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the reuqired property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReuqired() {
                    return reuqired;
                }

                /**
                 * Sets the value of the reuqired property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReuqired(String value) {
                    this.reuqired = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;a-1&gt;tekst-naslov"&gt;
             *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Naslov {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "required")
                @XmlSchemaType(name = "anySimpleType")
                protected String required;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the required property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRequired() {
                    return required;
                }

                /**
                 * Sets the value of the required property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRequired(String value) {
                    this.required = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="naslov" type="{a-1}tekst-naslov"/&gt;
         *         &lt;element name="autor" type="{a-1}t-autor"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "naslov",
            "autor"
        })
        public static class NaslovDeloPrerade {

            @XmlElement(required = true)
            protected String naslov;
            @XmlElement(required = true)
            protected TAutor autor;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the naslov property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaslov() {
                return naslov;
            }

            /**
             * Sets the value of the naslov property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaslov(String value) {
                this.naslov = value;
            }

            /**
             * Gets the value of the autor property.
             * 
             * @return
             *     possible object is
             *     {@link TAutor }
             *     
             */
            public TAutor getAutor() {
                return autor;
            }

            /**
             * Sets the value of the autor property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAutor }
             *     
             */
            public void setAutor(TAutor value) {
                this.autor = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="autor" type="{a-1}t-autor" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "autor"
        })
        public static class PodaciOAutoruNepodnosilac {

            @XmlElement(required = true)
            protected List<TAutor> autor;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the autor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the autor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TAutor }
             * 
             * 
             */
            public List<TAutor> getAutor() {
                if (autor == null) {
                    autor = new ArrayList<TAutor>();
                }
                return this.autor;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="lice" type="{a-1}t-lice"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lice"
        })
        public static class Podnosilac {

            @XmlElement(required = true)
            protected TLice lice;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the lice property.
             * 
             * @return
             *     possible object is
             *     {@link TLice }
             *     
             */
            public TLice getLice() {
                return lice;
            }

            /**
             * Sets the value of the lice property.
             * 
             * @param value
             *     allowed object is
             *     {@link TLice }
             *     
             */
            public void setLice(TLice value) {
                this.lice = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="opis-autorskog-dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="primer-autorskog-dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "opisAutorskogDela",
            "primerAutorskogDela"
        })
        public static class Prilozi {

            @XmlElement(name = "opis-autorskog-dela", required = true)
            protected String opisAutorskogDela;
            @XmlElement(name = "primer-autorskog-dela", required = true)
            protected String primerAutorskogDela;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the opisAutorskogDela property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOpisAutorskogDela() {
                return opisAutorskogDela;
            }

            /**
             * Sets the value of the opisAutorskogDela property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOpisAutorskogDela(String value) {
                this.opisAutorskogDela = value;
            }

            /**
             * Gets the value of the primerAutorskogDela property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimerAutorskogDela() {
                return primerAutorskogDela;
            }

            /**
             * Sets the value of the primerAutorskogDela property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimerAutorskogDela(String value) {
                this.primerAutorskogDela = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class PseudonimZnakAutora {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="adresa" type="{a-1}t-adresa"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "adresa"
        })
        public static class Punomocnik {

            @XmlElement(required = true)
            protected String ime;
            @XmlElement(required = true)
            protected String prezime;
            @XmlElement(required = true)
            protected TAdresa adresa;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link TAdresa }
             *     
             */
            public TAdresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link TAdresa }
             *     
             */
            public void setAdresa(TAdresa value) {
                this.adresa = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class VrstaAutorskogDela {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "required")
            @XmlSchemaType(name = "anySimpleType")
            protected String required;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the required property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequired() {
                return required;
            }

            /**
             * Sets the value of the required property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequired(String value) {
                this.required = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="naziv" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="adresa" type="{a-1}t-adresa"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "adresa"
    })
    public static class Zavod {

        @XmlElement(required = true)
        protected String naziv;
        @XmlElement(required = true)
        protected TAdresa adresa;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link TAdresa }
         *     
         */
        public TAdresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link TAdresa }
         *     
         */
        public void setAdresa(TAdresa value) {
            this.adresa = value;
        }

    }

}
