//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.12 at 09:29:15 PM GMT+01:00 
//


package main.java.com.xws.a1document.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t-autor-preminuo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t-autor-preminuo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{a-1}t-autor"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="godina-smrti" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t-autor-preminuo", propOrder = {
    "godinaSmrti"
})
public class TAutorPreminuo
    extends TAutor
{

    @XmlElement(name = "godina-smrti")
    protected int godinaSmrti;

    /**
     * Gets the value of the godinaSmrti property.
     * 
     */
    public int getGodinaSmrti() {
        return godinaSmrti;
    }

    /**
     * Sets the value of the godinaSmrti property.
     * 
     */
    public void setGodinaSmrti(int value) {
        this.godinaSmrti = value;
    }

}
